//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/ErrorCodeDefine.proto
namespace protocol
{
    [global::ProtoBuf.ProtoContract(Name=@"ErrorCodeDefine")]
    public enum ErrorCodeDefine
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"HANDLE_SHAKE_FAILE", Value=0)]
      HANDLE_SHAKE_FAILE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HANDLE_SHAKE_SUCCEED", Value=1)]
      HANDLE_SHAKE_SUCCEED = 1
    }
  
}