//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/ProtoDefine.proto
namespace protocol
{
    [global::ProtoBuf.ProtoContract(Name=@"ProtoDefine")]
    public enum ProtoDefine
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Handshake", Value=0)]
      Handshake = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StartGame", Value=1)]
      StartGame = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChessManaul", Value=2)]
      ChessManaul = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HitChess", Value=3)]
      HitChess = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WinGame", Value=4)]
      WinGame = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChessLocation", Value=5)]
      ChessLocation = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CloseConnect", Value=6)]
      CloseConnect = 6
    }
  
}